"""Shared constants for the overtaking simulation."""

PATTERN_SPARSE = "SPARSE"
PATTERN_CLUSTER = "CLUSTER"
PATTERN_MIXED = "MIXED"
PATTERN_OVERTAKING = "OVERTAKING"
PATTERNS = [PATTERN_SPARSE, PATTERN_CLUSTER, PATTERN_MIXED,PATTERN_OVERTAKING]

STATE_FOLLOW = "FOLLOW"
STATE_CHECKING = "CHECKING"
STATE_MERGE_OUT = "MERGE_OUT"
STATE_PASSING = "PASSING"
STATE_MERGE_BACK = "MERGE_BACK"
STATE_CLEAR = "CLEAR"

ACTION_LANE_LEFT = 0
ACTION_IDLE = 1
ACTION_LANE_RIGHT = 2
ACTION_FASTER = 3
ACTION_SLOWER = 4

GAP_REQUIRED_BEHIND = 20.0
GAP_REQUIRED_AHEAD = 30.0
SAFE_RETURN_GAP = 35.0
FOLLOW_DISTANCE_MIN = 20.0
FOLLOW_DISTANCE_OK = 40.0